name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Setup ⚙️
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install & Test ✅
        run: |
          yarn install
          yarn run test:ci

      - name: Quality Assurance 👌
        run: |
          npx dpdm --warning false --tree false --exit-code circular:1 src/**
          yarn run lint

      - name: Build 🔧
        run:
          yarn run build
